LOGDIR=${PROCDIR}/Log
TOUCHDIR=${PROCDIR}/Touch
LOCKDIR=${PROCDIR}/Lock
QCDIR=${PROCDIR}/QC
REPORTDIR=${PROCDIR}/Report

CON_TEMPDIR=${PROCDIR}/Temp.$$

LOCK_FILE="${LOCKDIR}/processing"
DONE_FILE="${TOUCHDIR}"/stage.${STAGE}.done
ERROR_FILE="${TOUCHDIR}"/stage.${STAGE}.error
STARTED_FILE="${TOUCHDIR}"/stage.${STAGE}.started

TRANSDIR=${PROCDIR}/Transformations
IMAGEDIR=${PROCDIR}/Images
SRCDIR=${PROCDIR}/Scripts

DTIDIR=${IMAGEDIR}/DTI

ORIGDIR=${DTIDIR}/0.Original
CORRDIR=${DTIDIR}/1.Correct
TFITDIR=${DTIDIR}/2.TensorFit
DIFPDIR=${DTIDIR}/3.DiffusionParameters
TRACKDIR=${DTIDIR}/4.Tractography
MNI_TRACKDIR=${TRACKDIR}/MNI
ATLAS_TRACKDIR=${DTIDIR}/5.TractographyFronAtlas
ATLAS_ON_FLAIR=${ATLAS_TRACKDIR}/flair
ATLAS_ON_DTI=${ATLAS_TRACKDIR}/DTI
ATLAS_ON_T1=${ATLAS_TRACKDIR}/t1

STRDIR=${IMAGEDIR}/structural
STR_IMPORTDIR=${STRDIR}/0.Original
STR_REGDIR=${STRDIR}/1.Registration
STR_SEEDDIR=${STRDIR}/3.TractographySeeds

TRACT_SCRDIR=${SRCDIR}/Tractography

MNIDIR=${FSLDIR}/data/standard
